### ISSUE TITLE
Refatoração - Implementar Herança/Interface para Pessoa

### ISSUE THREAD

**Issue by koziel101** [koziel101/TrabalhoFinalPoo#2]
Criar um novo Objeto do tipo "Pessoa" que seja abstrato (para ser utilizado herança ou interface). Os objeto do tipo Funcionario e Cliente herdarão/implementarão deste objeto.

**Comment by brenicio** [comment]
Estou criando a herança entre Pessoa -> Funcionario/Cliente, assim que concluir os testes de impacto nas outras classes vamos conseguir definir o tamanho de código que vamos refazer.

**Comment by brenicio** [comment]
Implementação de Herança da classe Pessoa -> Funcionário/Cliente concluída.
